### ISSUE TITLE
Miss the Online Demo

### ISSUE THREAD

**Issue by JamesJosephFinn** [syrusakbary/gdom#15]
For non-coders, the online demo was very unique and useful. There's nothing else like it online.

**Comment by mrVanDalo** [comment]
@JamesJosephFinn I created a docker container a while ago https://hub.docker.com/r/palo/gdom
maybe that helps you to spin up your private server.

**Comment by JamesJosephFinn** [comment]
@mrVanDalo I'll give it a go. Thanks man!
