### ISSUE TITLE
GraphiQL opened twice

### ISSUE THREAD

**Issue by tedmx** [syrusakbary/gdom#3]
Cheers for a very nice program!

When `gdom` is ran with `--test`, it seems the query test page is opened twice. Do you see the same behaviour on your system; and if yes, is it desired?

**Comment by syrusakbary** [comment]
The GraphiQL endpoint should be opened once by the web browser.
However if you change any python file involved in the process it will restart automatically the server and fire the "open url" again.

**Comment by tedmx** [comment]
Thanks so much syrusakbary! I hope I didn't sound confusing. What I've described happens immediately after `cmd.py --start` on my system, not after source file change. Browser opens the http://localhost:5000/ twice right after the script is started in terminal.
